name: run-tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: [8.3, 8.2, 8.1, 8.0]
                laravel: ["^11.0", "^10.0", "^9.0"]
                include:
                    - laravel: "^11.0"
                      testbench: 9.*
                    - laravel: "^10.0"
                      testbench: 8.*
                    - laravel: "^9.0"
                      testbench: 7.*
                exclude:
                    - laravel: "^11.0"
                      php: 8.1
                    - laravel: "^11.0"
                      php: 8.0
                    - laravel: "^10.0"
                      php: 8.0
                    - laravel: "^8.12"
                      php: 8.3

        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip
                  coverage: none

            - name: Setup problem matchers
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                  composer update --prefer-dist --no-interaction
            - name: Execute tests
              run: vendor/bin/pest
